name: Create Release
on:
  push:
    branches: 
      - main
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          BUILD_NUMBER: ${{ GITHUB_RUN_NUMBER }}
        with:
          tag_name: 0.0.${BUILD_NUMBER}
          release_name: Release 0.0.${BUILD_NUMBER}
          body: |
            Changes in this Release
            - ...
          draft: false
          prerelease: false
